
- name: Install Package Key
  apt_key: 
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Install repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main

- name: Install Kibana
  package: 
    name: kibana
    state: present

- name: Install Nginx
  package: 
    name: nginx
    state: present

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  tags: kibana-nginx

- name: Install kibana.conf for Nginx
  copy:
    src: files/kibana.conf
    dest: /etc/nginx/sites-enabled/kibana.conf
  notify: restart nginx
  tags: kibana-nginx


- name: Start Kibana service
  service:
    name: kibana
    state: started
    enabled: yes


